export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

// user register action constants

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

// constants for updating a user

export const USER_DETIALS_REQUEST = 'USER_DETIALS_REQUEST'
export const USER_DETIALS_SUCCESS = 'USER_DETIALS_SUCCESS'
export const USER_DETIALS_FAIL = 'USER_DETIALS_FAIL'
